Module11 task1
htmlacademy-javascript/2298777-kekstagram-28 pull request #11
Opened 2023-03-22 18:32 UTC by PapicBorovoi

2023-03-23 14:46 UTC, Pavel-Liteiniy requested changes

2023-03-23 14:46 UTC, Pavel-Liteiniy commented on js/filter-sliders.js
> +  effectsList.querySelector('#effect-none').checked = true;
Вынеси `effectsList.querySelector('#effect-none')` в константу, чтобы искать заново при каждом вызове `resetEffects()`

2023-03-23 14:46 UTC, Pavel-Liteiniy commented on js/messages.js
> +  alertContainer.style.zIndex = '100';
Давай сделаем утилитарную функцию, которая будет получать два аргумента - елемент и объект со стилями?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries
https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/setProperty

`const addStyleToElement = (element, style) => {
// преобразуем объект style в массив при помощи Object.entries
// итерируемся по этому массиву и при помощи element.style.setProperty(property, value) добавляем элементу все стили
}`

2023-03-23 14:46 UTC, Pavel-Liteiniy commented on js/messages.js
> +  alertContainer.style.zIndex = '100';
Ну а объект со стилями для alertContainer можно сделать константой

2023-03-23 14:46 UTC, Pavel-Liteiniy commented on js/server-api.js
> +    body: body
```suggestion
    body,
```

2023-03-23 14:46 UTC, Pavel-Liteiniy commented on js/validation.js
> +        errorCloseModal();
Давай здесь тоже будем использовать `closeModal`
[По заданию](https://up.htmlacademy.ru/javascript/28/project/kekstagram#kekstagram-3-5) нам нужно, чтобы данные не сбрасывались, поэтому допилим функцию closeModal - будем передавать аргумент c булевым значением и по нему определять нужно нам сбрасывать значения или нет.

2023-03-23 14:46 UTC, Pavel-Liteiniy commented on js/messages.js
> +const showPostSuccesMessage = () => {
```suggestion
const showPostSuccessMessage = () => {
```

2023-03-23 14:46 UTC, Pavel-Liteiniy commented on js/upload-form.js
> +  uploadModalCloseButton.removeEventListener('click', closeModal);
Кажется нет смысла при скрытии модуля удалять обработчик с кнопки?

2023-03-23 14:46 UTC, Pavel-Liteiniy commented on js/upload-form.js
> +  hideModal();
hideModal нигде не используется кроме closeModal? Давай объединим их и перенесем код из hideModal в closeModal

Лучше вынеси в отдельную функцию логику сброса данным

2023-03-23 14:46 UTC, Pavel-Liteiniy commented on js/upload-form.js
> +
Давай уберем этот обработчик и вынесем код из него внутрь `createUploadForm`

```
  uploadButton.addEventListener('change', () => {
    addOnScaleButton();
    addListenersOnEffects();
  }, {once: true});
```

2023-03-23 14:46 UTC, Pavel-Liteiniy commented on js/upload-form.js
>      uploadModalCloseButton.addEventListener('click', closeModal);
Этот обработчик тоже давай добавлять только один раз внутри функции `createUploadForm`

`uploadModalCloseButton.addEventListener('click', closeModal);`

2023-03-23 14:46 UTC, Pavel-Liteiniy commented on js/validation.js
> +        document.querySelector('#upload-file').addEventListener('click', (e) => {
Этот обработчик не нужен.
Добавь внутрь фукнции showModal логику с проверкой было ли уже выбрано какое-то значение или нет. Если было выбрано, то вызываем e.preventDefault();

2023-03-24 15:45 UTC, Pavel-Liteiniy requested changes

2023-03-24 15:45 UTC, Pavel-Liteiniy commented on js/upload-form.js
> +const closeModal = (isErrorOccurred = false) => () => {
Почему решил так написать? Кажется одной функции должно быть достаточно

`const closeModal = (isErrorOccurred = false) => {`

2023-03-24 15:45 UTC, Pavel-Liteiniy commented on js/upload-form.js
> +    uploadForm.querySelector('input[name="scale"]').value = '100%';
Давай это вынесем в функцию `showModal`

2023-03-24 15:45 UTC, Pavel-Liteiniy commented on js/upload-form.js
> +  if (uploadImgPreview.getAttribute('src') !== '') {
Этот `if` перенесем в обработчик клика по `uploadButton`

2023-03-24 15:45 UTC, Pavel-Liteiniy commented on js/upload-form.js
> +    const waitForUpload = () => {
Давай уберем функцию `waitForUpload` и попробуем чуть по другому сделать.
Сейчас эта функция в бесконечно цикле вызывается когда мы выбираем файл в открывшемся окне
А если мы не выберем файл и просто закроем окно, то она так и будет вызываться - memory leak(

2023-03-24 16:01 UTC, PapicBorovoi commented on js/upload-form.js
> +const closeModal = (isErrorOccurred = false) => () => {
Без замыкания не удалялся eventListener с документа который закрывал модальное окно по esc.

2023-03-25 08:05 UTC, PapicBorovoi commented on js/upload-form.js
> +    const waitForUpload = () => {
Посмотрел timeline вроде утечек не нашел. Если делать без setTimeout, то как? На stackoverflow именно этот вариант предлагался.

2023-03-27 04:46 UTC, Pavel-Liteiniy commented on js/upload-form.js
> +    const waitForUpload = () => {
Скинул пример в телеграме с видео
Давай попробуем добавить два обработчика вместо одного примерно так

```
  uploadButton.addEventListener('click', (e) => {
    if (uploadImgPreview.getAttribute('src') !== '') {
      e.preventDefault();
      showModal();
    }
  });

  uploadButton.addEventListener('change', () => {
    showModal();
  });
```

2023-03-27 04:46 UTC, Pavel-Liteiniy commented on js/upload-form.js
> +const closeModal = (isErrorOccurred = false) => () => {
Вроде удаляется - проверь еще раз, пожалуйста?))
Скинул тебе видео в телеграм

2023-03-27 09:57 UTC, merged