Module8 task2
htmlacademy-javascript/2298777-kekstagram-28 pull request #8
Opened 2023-03-07 11:06 UTC by PapicBorovoi

Страшно, очень страшно

2023-03-07 11:08 UTC, PapicBorovoi commented
Очень долго разбирался как нормально удалить обработчик кнопки. Получилось только с замыканием.

2023-03-07 14:45 UTC, Pavel-Liteiniy requested changes

2023-03-07 14:45 UTC, Pavel-Liteiniy commented on js/full-picture-render.js
> +
добавь переменную, в которой будем считать количество отрисованных комментариев

```suggestion
let visibleCommentsCounter = NUMBER_OF_VISIBLE_COMMENTS;
```

2023-03-07 14:45 UTC, Pavel-Liteiniy commented on js/full-picture-render.js
>    if (isEscapeKeydown(evt)) {
Давай здесь будем использовать `closeBigPicture` чтобы не дублировать код 
И давай добавим в `closeBigPicture` логику, что когда мы закрываем модальное окно, то сбрасываем значение переменной visibleCommentsCounter к первоначальному

2023-03-07 14:45 UTC, Pavel-Liteiniy commented on js/full-picture-render.js
> +const getCommentData = (photo) => {
Давай уберем здесь замыкание, и немного упростим эту функцию.
Все что она должна будет делать - это получать массив комментариев и отрисовывать его

2023-03-07 14:45 UTC, Pavel-Liteiniy commented on js/full-picture-render.js
> +  const addCommentsCount = () => {
давай вынесем эту функцию из renderBigPicture и добавим ей два аргумента: количество отрисованных комментариев и общее количество комментариев

- Попробуй внутри использовать метод .append()
- Подумай как можно внутри заменить `if (photo.comments.length <= NUMBER_OF_VISIBLE_COMMENTS)`
на `Math.min(showedCount, allCount)`
- Давай будем создавать элементы через метод `document.createElement`

2023-03-07 14:45 UTC, Pavel-Liteiniy commented on js/full-picture-render.js
> +      bigPicture.querySelector('.comments-loader').classList.add('hidden');
Давай вынесем в отдельные функции логику скрытия и показа кнопки

```suggestion
      const showCommentLoaderButton = (onCommentButtonClick) => {
          bigPicture.querySelector('.comments-loader').classList.remove('hidden');
          bigPicture.addEventListener('click', onCommentButtonClick);
      };
```

2023-03-07 14:45 UTC, Pavel-Liteiniy commented on js/full-picture-render.js
> +    const socialCommentsCount = socialComments.children.length;
Чтобы функция `onCommentButtonClick` запоминала с каким `photo` она работает будем объявлять её внутри `renderBigPicture`

Но, рефакторинг вынесет большую часть кода и логики за пределы так что внутри этой функции нам останется сделать следующее
- вызываем функцию добавляения комментариев (чтобы передать в неё нужное количество комментариев можно воспользоваться методом `array.slice()`)
- увеличиваем счетчик `visibleCommentsCounter`
- вызываем функцию которая обновляет информацию внутри `.social__comment-count` 
- проверяем нужно ли вызвать функцию, которая скроет кнопку и удалит у неё обработчик события и вызваем эту функцию если это нужно сделать

2023-03-08 11:35 UTC, PapicBorovoi commented
Не получается вынести функции зависящие от onCommentButtonClick из-за области видимости. Также заметил что closeBigPicture не убирал обработчик с кнопки загрузки коментариев, поэтому чтобы это исправить пришлось переносить функции  закрытия окна внутрь renderBigPicture.

2023-03-08 14:26 UTC, Pavel-Liteiniy requested changes

2023-03-08 14:26 UTC, Pavel-Liteiniy commented on js/full-picture-render.js
> +  let numberToShow = NUMBER_OF_VISIBLE_COMMENTS > photo.comments.length ?
```suggestion
  let numberToShow = Math.min(NUMBER_OF_VISIBLE_COMMENTS, photo.comments.length)
```

2023-03-08 14:26 UTC, Pavel-Liteiniy commented on js/full-picture-render.js
> +  photo.comments.forEach((comment) => {
Замени `forEach` на метод `map`

2023-03-08 14:26 UTC, Pavel-Liteiniy commented on js/full-picture-render.js
> +const addCommentsToArray = (photo) => {
```suggestion
const createComments = (photo) => {
```

2023-03-08 14:26 UTC, Pavel-Liteiniy commented on js/full-picture-render.js
> +    numberToShow = comments.length - shownComments < NUMBER_OF_VISIBLE_COMMENTS ?
```suggestion
    numberToShow = Math.min(NUMBER_OF_VISIBLE_COMMENTS, (comments.length - shownComments))
```

2023-03-08 14:27 UTC, Pavel-Liteiniy commented
Проверь, пожалуйста, почему упали проверки в PR
<img width="889" alt="image" src="https://user-images.githubusercontent.com/47995886/223738999-165094b1-ddeb-416e-b21d-0d14d9c60a71.png">

2023-03-08 14:29 UTC, Pavel-Liteiniy commented
> Не получается вынести функции зависящие от onCommentButtonClick из-за области видимости. Также заметил что closeBigPicture не убирал обработчик с кнопки загрузки коментариев, поэтому чтобы это исправить пришлось переносить функции закрытия окна внутрь renderBigPicture.

Как вариант ты можешь передавать `onCommentButtonClick` через параметры в зависящие функции

2023-03-09 05:19 UTC, merged